
name: srganenv_gpu
dependencies:
- python=3.7.5
- cudatoolkit=10.1
- pip
- tqdm=4.32.1
- Pillow=5.1.0
- matplotlib=3.1.1
- pip:
  - notebook
  - scikit-image==0.15.0
  - numpy==1.14.5
  - pandas
  - matplotlib
